name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        port: 22
        script: |
          ls
          cd flower-nest
          sudo git pull origin main
          /home/slasher/.nvm/versions/node/v22.15.0/bin/npm install
          /home/slasher/.nvm/versions/node/v22.15.0/bin/pm2
          sudo -E pm2 restart all or any other command to restart all
